version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-mysql-golang-campus
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=golangcampus
    volumes:
      - "/Users/arialamsyah/Desktop/SoftwareEngineer/Backend/GO/Projects/fastcampus/fastcampus_mysql:/var/lib/mysql"
      